"""
File: Random_Numbers.py
------------------------
This program prints a series of random numbers in the
range from MIN_RANDOM to MAX_RANDOM, inclusive
"""

import random

NUM_RANDM=10
MIN_RANDM=0
MAX_RANDM=100

def main():
    """
    The find_random_function is called from the main function
    """

    find_random_numbers()


"""The find_random_function finds 10 random numbers and prints them one by one"""
def find_random_numbers():
    """pre-condition-1
       post-condition-10
    """
    for i in range(10):
        """This variable stores the random number generated by the random.randint function"""
        random_number = random.randint(MIN_RANDM,MAX_RANDM)
        print(random_number)


"""
# This provided line is required at the end of Python file 
  to call the main() function.
# It allows the script to be run as the main program or imported 
  without executing the main function immediately.
"""
if __name__ == '__main__':
    main()

